//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//
//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
//Let us list the factors of the first seven triangle numbers:
//
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.
//
//What is the value of the first triangle number to have over five hundred divisors?
public class test012 {

	public static void main(String[] args) {
		long add=1;
		long num=1;
		int amout=0;
		long sqrt=0;
		while(true) {
			sqrt=(long) Math.sqrt(num);
			if(num==sqrt*sqrt)
				amout=1;
			for(long i=1;i<sqrt;i++) {
				if(isFactor(i,num))
					amout+=2;
			}
			System.out.println(amout);
			if(amout>500) {
				System.out.println(num);
				break;
			}
			amout=0;
			add++;
			num+=add;
		}

	}
	static boolean isFactor(long b,long a) {
		return a==a/b*b;
	}
}
